name: Manipulations for HTTP GET

on:
  workflow_dispatch:  # Allows manual triggering
  issues:
    types: [opened]

jobs:
  matrix-repos:
    runs-on: ubuntu-latest

    outputs:
      repos: ${{ steps.extract.outputs.repos }}
    
    steps:
      - name: Retrieve the list of common labels
        id: extract
        run: |
          curl --fail -o labels.json "https://w3c.github.failure/common-labels.json"
          REPOS=`jq -c -r '[.[]."repo-request"] | map(select(.!=null)) | unique' labels.json`
          echo "repos=$REPOS" >> "$GITHUB_OUTPUT"

  do-something:
    runs-on: ubuntu-latest
    needs: matrix-repos
    strategy:
      matrix:
        repo: ${{ fromJSON(needs.matrix-repos.outputs.repos) }}
        
    steps:
      - name: Process ${{ matrix.repo }}
        env:
          repo: ${{ matrix.repo }}
        run: |
          echo "$repo"
          echo "Processing $repo"

        
