name: Manipulations for HTTP GET

on:
  workflow_dispatch:  # Allows manual triggering
  issues:
    types: [labeled]

jobs:
  matrix-repos:
    runs-on: ubuntu-latest

    outputs:
      repos: ${{ steps.extract.outputs.repos }}
    
    steps:
      - name: Retrieve the list of common labels
        id: extract
        run: |
          curl --fail -o labels.json "https://w3c.github.io/common-labels.json"
          REPOS=`jq -c -r '[.[]."repo-request"] | map(select(.!=null)) | unique' labels.json`
          echo "repos=$REPOS" >> "$GITHUB_OUTPUT"

  do-something:
    runs-on: ubuntu-latest
    needs: matrix-repos
    strategy:
      matrix:
        repo: ${{ fromJSON(needs.matrix-repos.outputs.repos) }}
        
    steps:
    - name: Create issue payload file
      env:
        ISSUE_CONTEXT: ${{ toJSON(github.event.issue) }}
      run: echo "$ISSUE_CONTEXT" > issue.json

    - name: create issue in ${{ matrix.repo }}
      env:
        repo: ${{ matrix.repo }}
        GITHUB_TOKEN: ${{ secrets.W3CBOT_TOKEN }}
      run: |
        ASSIGNEES=$(jq -c -r '.assignees.[].login' issue.json | sed -s 's/^/cc @/')
        echo $ASSIGNEES

        
